services:
  mysql:
    container_name: mysql
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      TZ: Asia/Tokyo
    image: mysql:8.0.28
    networks:
      - localhost
    restart: always
    volumes:
      - ./conf/:/etc/mysql/conf.d/
      - ./init/:/docker-entrypoint-initdb.d/
      - ./log/:/var/log/
      - mysql-volume:/var/lib/mysql/

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_USER: ${MYSQL_USER}
      VIRTUAL_HOST: phpmyadmin.localhost
    image: phpmyadmin/phpmyadmin:5.1.3
    networks:
      - localhost
    restart: always

networks:
  localhost:
    external: true

volumes:
  mysql-volume:
    name: mysql-volume
