version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.26
    ports:
      - 3306:3306
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - ./conf/:/etc/mysql/conf.d/
      - ./log/:/var/log/
      - mysql_volume:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    networks:
      - localhost
    restart: always
  phpmyadmin:
    container_name: php-my-admin
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      VIRTUAL_HOST: mysql.localhost
      VIRTUAL_PORT: 80
    networks:
      - localhost
    restart: always
    links:
      - mysql
volumes:
  mysql_volume:
    name: mysql_volume
networks:
  localhost:
    external: true
